services:
  automator:
    build: .
    environment:
      - STARKNET_RPC=${STARKNET_RPC}
      - STARKNET_PRIVATE_KEY=${STARKNET_PRIVATE_KEY}
      - STARKNET_ACCOUNT_ADDRESS=${STARKNET_ACCOUNT_ADDRESS}
      - FOSSIL_API_KEY=${FOSSIL_API_KEY}
      - FOSSIL_API_URL=${FOSSIL_API_URL}
      - VAULT_ADDRESSES=${VAULT_ADDRESSES}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - ./logs:/var/log/cron
    restart: always